### ISSUE TITLE
How do I access the rdbg REPL?

### ISSUE THREAD

**Issue by monochromec** [ruby/vscode-rdbg#66]
When trying to enable post-mortem debugging via the rdbg command `config set portmortem true` I get the error message no "NoMethodError...Undefined method 'postmortem'" when using the normal debug console. 

How do I access the rdbg REPL from VSCode correctly?

**Comment by ko1** [comment]
Now nothing to do.

1. `~/.rdbgrc` will be loaded at first.
2. `debugger do: 'config set postmortem true'` in your source code.

BTW I didn't test postmortem mode on vscode, so you can find another issue.

**Comment by monochromec** [comment]
@ko1 Thanks for the hint.
What I did in order to enable post-mortem debugging and have the REPL at my disposal was to put `config set postmortem true` in my ~/.rdbgrc as outlined above, leaving the original Ruby source code unmodified. This is works independently of a VS Code deployment.
